# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'to-mvn-repo'
    repository: 'nodejs'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo $(Build.BuildId) > $(Build.ArtifactStagingDirectory)/buildid.txt
        displayName: 'Create Build ID File'