# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
  pipelines:
  - pipeline: securitylib # Name of the pipeline resource.
    source: TodoList-NodeJS-Backend-build # The name of the pipeline referenced by this pipeline resource.
#    project: FabrikamProject # Required only if the source pipeline is in another project
    trigger: 
     branches:
     - master
#   true # Run app-ci pipeline when any run of security-lib-ci completes

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az aks start --name burhanuddin-kuber --resource-group nodejs-rg'

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'kubecluster-sp'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'deployment/deployment.yml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'

