trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'mvnrepo'
    repository: 'nodejs'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'kubecluster-sp'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'deployment.yml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'