# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- none

resources:
  pipelines:
  - pipeline: securitylib # Name of the pipeline resource.
    source: TodoList-NodeJS-Backend-build # The name of the pipeline referenced by this pipeline resource.
    trigger: 
     branches:
     - master

pool:
  vmImage: ubuntu-latest

variables:
  imageTag: '$imageTag'

steps:
- script: |
    buildId=$(cat $(System.ArtifactsDirectory)/BuildID/buildid.txt)
    echo "Build ID is $buildId"
  displayName: 'Use Build ID'

- task: DownloadBuildArtifacts@1
  displayName: 'Download Build ID Artifact'
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'BuildID'
    downloadPath: '$(System.ArtifactsDirectory)/BuildID'


- task: replacetokens@5
  inputs:
    rootDirectory: 'deployment'
    targetFiles: '**/deployment.yml'
    encoding: 'auto'
    tokenPattern: 'default'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true

- task: AzureCLI@2
  inputs:
    azureSubscription: 'to-my-k8s-portal'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './script1.sh'


- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'to-my-k8s-portal'
    azureResourceGroup: 'cicd-mvn'
    kubernetesCluster: 'mvn-spring'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'deployment/deployment.yml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'to-my-k8s-portal'
    azureContainerRegistry: 'mvnrepo.azurecr.io'
    secretName: 'burhanuddin-acr-secret'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'to-my-k8s-portal'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './script2.sh'