# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
  pipelines:
  - pipeline: securitylib # Name of the pipeline resource.
    source: TodoList-NodeJS-Backend-build # The name of the pipeline referenced by this pipeline resource.
    trigger: 
     branches:
     - master

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'my-portal-for-k8s'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './script2.sh'

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'my-portal-for-k8s'
    azureResourceGroup: 'nodejs-rg'
    kubernetesCluster: 'burhanuddin-kuber'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'deployment/deployment.yml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'my-portal-for-k8s'
    azureContainerRegistry: 'mvnrepo.azurecr.io'
    secretName: 'burhanuddin-acr-secret'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'my-portal-for-k8s'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './script.sh'



#- task: AzureCLI@2
#  inputs:
#    azureSubscription: 'kubernetes-sp'
#    scriptType: 'bash'
#    scriptLocation: 'inlineScript'
#    inlineScript: 'az aks start --name burhanuddin-kuber --resource-group nodejs-rg'
