trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'nodejs'
  imageTag: '514'
  imageRepository: 'mvnrepo.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'

stages:
- stage: BuildAndPush
  jobs:
  - job: BuildAndPushJob
    displayName: 'Build and Push Docker Image'
    steps:

    - task: Docker@2
      inputs:
        repository: 'nodejs'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(imageTag)'
        addPipelineData: false
        addBaseImageData: false

    - script: 
        docker tag nodejs:$(imageTag) mvnrepo.azurecr.io/nodejs:$(imageTag)
        az acr login -n mvnrepo.azurecr.io --username mvnrepo --password wFzE/+c2VTXgp4bCqZjrBEfJ8bXC/LHNvxGb0z/5+1+ACRDP4yVJ
        docker push mvnrepo.azurecr.io/nodejs:$(imageTag)
      displayName: 'Docker Image tag and push'

    - script:
        docker save -o /home/vsts/work/1/a/nodejs.tar mvnrepo.azurecr.io/nodejs:$(imageTag)
      displayName: 'Docker Image saving to tar file'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'docker-image'
        publishLocation: 'Container'