# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
  tag: '#{image_tag}#'
  vmImageName: 'ubuntu-latest'
  envName: 'poc-releases'
  docker_image_name: API
  imagePullSecret: 'mvnrepo.azurecr.io'
  dockerRegistryServiceConnection: 'Azure Container Registry'

trigger:
- none

resources:
  pipelines:
  - pipeline: securitylib # Name of the pipeline resource.
    source: TodoList-NodeJS-Backend-build # The name of the pipeline referenced by this pipeline resource.
    trigger: 
     branches:
     - master

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'my-portal-for-k8s'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './script2.sh'

- task: replacetokens@5
  inputs:
    rootDirectory: 'deployment'
    targetFiles: '**/deployment.yml'
    encoding: 'auto'
    tokenPattern: 'default'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'my-portal-for-k8s'
    azureResourceGroup: 'nodejs-rg'
    kubernetesCluster: 'burhanuddin-kuber'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'deployment/deployment.yml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'my-portal-for-k8s'
    azureContainerRegistry: 'mvnrepo.azurecr.io'
    secretName: 'burhanuddin-acr-secret'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'my-portal-for-k8s'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './script.sh'






# and this pipeline trigger from the source build
# now deploy to the AKS cluster with service principal conection of kubernetes service and 
# creating secrets cause pulling the image from ACR to kubernets service.ACR is private registry.
# after deploy to the AKS clusetr, now i am start and stop the cluster with command, in shellscript whatever i mentioned the commands,so it will take from there. 
# and i mentioned the service name, AKS credentials, External Ip of servcie name and health check 



#- task: AzureCLI@2
#  inputs:
#    azureSubscription: 'kubernetes-sp'
#    scriptType: 'bash'
#    scriptLocation: 'inlineScript'
#    inlineScript: 'az aks start --name burhanuddin-kuber --resource-group nodejs-rg'
