apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1  # Adjust as needed
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: shaikburhanuddin/nodejs-project:1.0.0  # Replace with your Node.js app image
        imagePullPolicy: "Always"  # Change to your image pull policy
        ports:
        - containerPort: 3000  # Adjust as needed
        env:
          - name: DATABASE_URL
            value: "mongodb://mongodb-service:27017/myDataBase"
      imagePullSecrets:
      - name: my-secret
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 3001  # Expose the service on port 3001, adjust as needed
      targetPort: 3000  # Port on which your Node.js app is running
  type: NodePort  # Adjust based on your infrastructure (e.g., NodePort, ClusterIP)
  ---
  