apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1  # Adjust as needed
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: shaikburhanuddin/nodejs-project:1.0.0  # Replace with your Node.js app image
        imagePullPolicy: "Always"  # Change to your image pull policy
        ports:
        - containerPort: 3000  # Adjust as needed
        env:
          - name: DATABASE_URL
            value: "mongodb://mongodb-service:27017/myDataBase"
      imagePullSecrets:
      - name: my-secret
---
