version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports: 
      - "27017:27017"

  nodejs:
    image: nodejs-image
    container_name: shaikburhan
    ports:
      - "3003:3000"
    environment:
      PORT: "3000"
      DATABASE_URL: mongodb://mongodb:27017/myDataBase
    depends_on:
      - mongodb