kubectl create secret docker-registry acr-secret \
    --docker-server: 'https://index.docker.io/v1/'
    --docker-username: 'shaikburhanuddin'
    --docker-password: 'Gousesohail@7764'
    --docker-email: 'shaiksohail55149@gmail.com'


kubectl create secret docker-registry my-secret \
  --docker-server='https://index.docker.io/v1/' \
  --docker-username='shaikburhanuddin' \
  --docker-password='Gousesohail@7764' \
  --docker-email='shaiksohail55149@gmail.com'



kubectl create secret docker-registry my-mini-secret \
  --docker-server='192.168.59.107:5000 \
  --docker-username='shaikburhanuddin' \
  --docker-password='Gousesohail@7764' \
  --docker-email='shaiksohail55149@gmail.com'

